apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-git-private-repo-run-
  labels:
    tekton.dev/pipeline: clone-git-private-repo
spec:
  pipelineRef:
    name: clone-git-private-repo
  params:
    - name: private-github-repo-url
      value: git@github.com:ega4432/private-repository.git
  workspaces:
    - name: my-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Mi
    - name: ssh-creds
      secret:
        secretName: ssh-credential

