apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-credentials
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    XXXXXXXXXXXXXXX
  # cat ~/.ssh/id_clone_private_repo_rsa | base64
