apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: output-readme
spec:
  workspaces:
  - name: source
  steps:
  - name: output
    image: busybox:latest
    script: |
      #!/bin/sh
      set -eux
      cd workspace/source
      if [ -f README.md ]; then
        cat README.md
      else
        echo "Not found README.md"
        exit 1
      fi
